import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root',
})
export class DataService {
  public testSavingsAccount: any[] = [
    {
      accountNumber: 100378340,
      customize: 'Ahorro vacacional',
      currentBalance: 5000,
    },
    {
      accountNumber: 100378340,
      customize: 'Ahorro navideño',
      currentBalance: 400,
    },
    {
      accountNumber: 204678340,
      customize: 'Ahorro escolar',
      currentBalance: 999999999,
    },
  ];

  public testArrayData: any[] = [
    {
      date: '02/02/2022',
      id: '101036',
      type: 'En APP',
      description: 'Transferencia',
      amount: -750,
      records: 2,
      fullName: 'Jane Cooper',
      status: 'Rechazado',
      statusType: 'error',
      coin: 'DOP',
      idBank: '126112',
      username: 'usuario20m5',
      email: 'ejemplo@losguacalitos.com',
      userStatus: 'Bloqueado',
      state: false,
      country: 'Costa Rica',
      alias: 'Cuenta Personal',
      bank: 'Popular',
      business: 'Hidroelectricidad',
      category: 'Electricidad',
      aliasInvoice: 'Pago Luz',
    },
    {
      date: '01/02/2022',
      id: '101562',
      type: 'Internacional',
      description: 'Transferencia',
      amount: -9000,
      records: 2,
      fullName: 'Jane Cooper',
      status: 'Aprobado',
      statusType: 'success',
      coin: 'DOP',
      idBank: '126112',
      username: 'usuario20m5',
      email: 'ejemplo@losguacalitos.com',
      userStatus: 'Activo',
      state: false,
      country: 'República Dominicana',
      alias: 'Cuenta Comercio',
      bank: 'APAP',
      business: 'Hidroelectricidad',
      category: 'Electricidad',
      aliasInvoice: 'Pago Luz',
    },
    {
      date: '27/01/2022',
      id: '105656',
      type: 'En APP',
      description: 'Transferencia',
      amount: 60,
      records: 2,
      fullName: 'Jane Cooper',
      status: 'Pendiente',
      statusType: 'warning',
      coin: 'DOP',
      idBank: '126112',
      username: 'usuario20m5',
      email: 'ejemplo@losguacalitos.com',
      userStatus: 'Inactivo',
      state: false,
      country: 'Costa Rica',
      alias: 'Cuenta familia',
      bank: 'Davivienda',
      business: 'Hidroelectricidad',
      category: 'Electricidad',
      aliasInvoice: 'Pago Luz',
    },
    {
      date: '14/01/2022',
      id: '656262',
      type: 'En APP',
      description: 'Transferencia',
      amount: 365,
      records: 2,
      fullName: 'Jane Cooper',
      status: 'Aprobado',
      statusType: 'success',
      coin: 'DOP',
      idBank: '126112',
      username: 'usuario20m5',
      email: 'ejemplo@losguacalitos.com',
      userStatus: 'Activo',
      state: false,
      country: 'Costa Rica',
      alias: 'Cuenta familia',
      bank: 'Davivienda',
      business: 'Hidroelectricidad',
      category: 'Electricidad',
      aliasInvoice: 'Pago Luz',
    },
    {
      date: '12/01/2022',
      id: '145289',
      type: 'En APP',
      description: 'Transferencia',
      amount: 650,
      records: 2,
      fullName: 'Jane Cooper',
      status: 'Enviado',
      statusType: 'info',
      coin: 'DOP',
      idBank: '126112',
      username: 'usuario20m5',
      email: 'ejemplo@losguacalitos.com',
      userStatus: 'Inactivo',
      state: false,
      country: 'Ecuador',
      alias: 'Cuenta personal',
      bank: 'Pichincha',
      business: 'Hidroelectricidad',
      category: 'Electricidad',
      aliasInvoice: 'Pago Luz',
    },
    {
      date: '31/12/2021',
      id: '101742',
      type: 'Internacional',
      description: 'Transferencia',
      amount: 50,
      records: 2,
      fullName: 'Jane Cooper',
      status: 'Rechazado',
      statusType: 'error',
      coin: 'DOP',
      idBank: '126112',
      username: 'usuario20m5',
      email: 'ejemplo@losguacalitos.com',
      userStatus: 'Bloqueado',
      state: false,
      country: 'Ecuador',
      alias: 'Cuenta personal',
      bank: 'Pichincha',
      business: 'Hidroelectricidad',
      category: 'Electricidad',
      aliasInvoice: 'Pago Luz',
    },
    {
      date: '24/12/2021',
      id: '561632',
      type: 'En APP',
      description: 'Transferencia',
      amount: 12302,
      records: 2,
      fullName: 'Jane Cooper',
      status: 'Pendiente',
      statusType: 'warning',
      coin: 'DOP',
      idBank: '126112',
      username: 'usuario20m5',
      email: 'ejemplo@losguacalitos.com',
      userStatus: 'Inactivo',
      state: false,
      country: 'Ecuador',
      alias: 'Cuenta personal',
      bank: 'Pichincha',
      business: 'Hidroelectricidad',
      category: 'Electricidad',
      aliasInvoice: 'Pago Luz',
    },
    {
      date: '01/01/2022',
      id: '101562',
      type: 'En APP',
      description: 'Transferencia',
      amount: 8965,
      records: 2,
      fullName: 'Jane Cooper',
      status: 'Rechazado',
      statusType: 'error',
      coin: 'DOP',
      idBank: '126112',
      username: 'usuario20m5',
      email: 'ejemplo@losguacalitos.com',
      userStatus: 'Bloqueado',
      state: false,
      country: 'Costa Rica',
      alias: 'Cuenta Personal',
      bank: 'Popular',
      business: 'Hidroelectricidad',
      category: 'Electricidad',
      aliasInvoice: 'Pago Luz',
    },
    {
      date: '24/01/2022',
      id: '101534',
      type: 'Otros Bancos',
      description: 'Transferencia',
      amount: 3620,
      records: 2,
      fullName: 'Jane Cooper',
      status: 'Pendiente',
      statusType: 'warning',
      coin: 'DOP',
      idBank: '126112',
      username: 'usuario20m5',
      email: 'ejemplo@losguacalitos.com',
      userStatus: 'Inactivo',
      state: false,
      country: 'Costa Rica',
      alias: 'Cuenta Personal',
      bank: 'Popular',
      business: 'Hidroelectricidad',
      category: 'Electricidad',
      aliasInvoice: 'Pago Luz',
    },
    {
      date: '01/02/2022',
      id: '156562',
      type: 'En APP',
      description: 'Transferencia',
      amount: 45,
      records: 2,
      fullName: 'Jane Cooper',
      status: 'Rechazado',
      statusType: 'error',
      coin: 'DOP',
      idBank: '126112',
      username: 'usuario20m5',
      email: 'ejemplo@losguacalitos.com',
      userStatus: 'Bloqueado',
      state: false,
      country: 'Colombia',
      alias: 'Cuenta Personal',
      bank: 'Bancolombia',
      business: 'Hidroelectricidad',
      category: 'Electricidad',
      aliasInvoice: 'Pago Luz',
    },
    {
      date: '01/02/2022',
      id: '101569',
      type: 'Internacional',
      description: 'Transferencia',
      amount: 12.5,
      records: 2,
      fullName: 'Jane Cooper',
      status: 'Rechazado',
      statusType: 'error',
      coin: 'DOP',
      idBank: '126112',
      username: 'usuario20m5',
      email: 'ejemplo@losguacalitos.com',
      userStatus: 'Bloqueado',
      state: false,
      country: 'Colombia',
      alias: 'Cuenta Personal',
      bank: 'Bancolombia',
      business: 'Hidroelectricidad',
      category: 'Electricidad',
      aliasInvoice: 'Pago Luz',
    },
    {
      date: '23/02/2022',
      id: '101536',
      type: 'En APP',
      description: 'Transferencia',
      amount: 1563,
      records: 2,
      fullName: 'Jane Cooper',
      status: 'Rechazado',
      statusType: 'error',
      coin: 'DOP',
      idBank: '126112',
      username: 'usuario20m5',
      email: 'ejemplo@losguacalitos.com',
      userStatus: 'Bloqueado',
      state: false,
      country: 'Colombia',
      alias: 'Cuenta Personal',
      bank: 'Bancolombia',
      business: 'Hidroelectricidad',
      category: 'Electricidad',
      aliasInvoice: 'Pago Luz',
    },
    {
      date: '01/02/2022',
      id: '104512',
      type: 'Otros Bancos',
      description: 'Transferencia',
      amount: 200,
      records: 2,
      fullName: 'Jane Cooper',
      status: 'Rechazado',
      statusType: 'error',
      coin: 'DOP',
      idBank: '126112',
      username: 'usuario20m5',
      email: 'ejemplo@losguacalitos.com',
      userStatus: 'Bloqueado',
      state: false,
      country: 'El Salvador',
      alias: 'Cuenta familiar',
      bank: 'BAC Credomatic',
      business: 'Hidroelectricidad',
      category: 'Electricidad',
      aliasInvoice: 'Pago Luz',
    },
    {
      date: '01/02/2022',
      id: '126445',
      type: 'En APP',
      description: 'Transferencia',
      amount: 369,
      records: 2,
      fullName: 'Jane Cooper',
      status: 'Rechazado',
      statusType: 'error',
      coin: 'DOP',
      idBank: '126112',
      username: 'usuario20m5',
      email: 'ejemplo@losguacalitos.com',
      userStatus: 'Bloqueado',
      state: false,
      country: 'El Salvador',
      alias: 'Cuenta familiar',
      bank: 'BAC Credomatic',
      business: 'Hidroelectricidad',
      category: 'Electricidad',
      aliasInvoice: 'Pago Luz',
    },
    {
      date: '18/02/2022',
      id: '105151',
      type: 'En APP',
      description: 'Transferencia',
      amount: 420,
      records: 2,
      fullName: 'Jane Cooper',
      status: 'Rechazado',
      statusType: 'error',
      coin: 'DOP',
      idBank: '126112',
      username: 'usuario20m5',
      email: 'ejemplo@losguacalitos.com',
      userStatus: 'Bloqueado',
      state: false,
      country: 'El Salvador',
      alias: 'Cuenta personal',
      bank: 'BAC Credomatic',
      business: 'Hidroelectricidad',
      category: 'Electricidad',
      aliasInvoice: 'Pago Luz',
    },
    {
      date: '01/02/2022',
      id: '126112',
      type: 'Internacional',
      description: 'Transferencia',
      amount: 530,
      records: 2,
      fullName: 'Jane Cooper',
      status: 'Rechazado',
      statusType: 'error',
      coin: 'DOP',
      idBank: '126112',
      username: 'usuario20m5',
      email: 'ejemplo@losguacalitos.com',
      userStatus: 'Bloqueado',
      state: false,
      country: 'El Salvador',
      alias: 'Cuenta familiar',
      bank: 'BAC Credomatic',
      business: 'Hidroelectricidad',
      category: 'Electricidad',
      aliasInvoice: 'Pago Luz',
    },
    {
      date: '01/02/2022',
      id: '556166',
      type: 'En APP',
      description: 'Transferencia',
      amount: 1.25,
      records: 2,
      fullName: 'Jane Cooper',
      status: 'Pendiente',
      statusType: 'warning',
      coin: 'DOP',
      idBank: '126112',
      username: 'usuario20m5',
      email: 'ejemplo@losguacalitos.com',
      userStatus: 'Inactivo',
      state: false,
      country: 'El Salvador',
      alias: 'Cuenta familiar',
      bank: 'BAC Credomatic',
      business: 'Hidroelectricidad',
      category: 'Electricidad',
      aliasInvoice: 'Pago Luz',
    },
  ];

  public testArrayDataProductsProcess: any[] = [
    {
      requestNumber: '10037834060',
      productType: 'Cuenta Balance Mínimo Flexible',
      creationDate: '25 Ago. 2021',
      status: 'En análisis',
      statusType: 'warning',
      state: false,
    },
    {
      requestNumber: '10037834060',
      productType: 'Préstamos con Garantía de Depósitos',
      creationDate: '25 Ago. 2021',
      status: 'Incompleta',
      statusType: 'error',
      state: false,
    },
    {
      requestNumber: '10037834060',
      productType: 'Tarjeta de Crèdito PYME APAP',
      creationDate: '25 Ago. 2021',
      status: 'Aprobada',
      statusType: 'success',
      state: false,
    },
    {
      requestNumber: '10037834060',
      productType: 'Bolso Protegido',
      creationDate: '25 Ago. 2021',
      status: 'Incompleta',
      statusType: 'error',
      state: false,
    },
    {
      requestNumber: '10037834060',
      productType: 'Certificado sin Redención Anticipada',
      creationDate: '25 Ago. 2021',
      status: 'En análisis',
      statusType: 'warning',
      state: false,
    },
    {
      requestNumber: '10037834060',
      productType: 'Tarjeta de Crédito Distribución Ochoa',
      creationDate: '25 Ago. 2021',
      status: 'Aprobada',
      statusType: 'success',
      state: false,
    },
  ];

  public testArrayData2: any[] = [
    {
      creditAccount: '99999999999',
      suppliers: 'Jane Cooper',
      beneficiaryType: 'APAP',
      bankId: '10101010',
      amount: 999999999.99,
      coin: 'DOP',
      status: 'Error',
      statusType: 'error',
      state: false,
    },
    {
      creditAccount: '1019833919',
      suppliers: 'Robert Fox',
      beneficiaryType: 'Internacional',
      bankId: '10123453',
      amount: 999999999.99,
      coin: 'DOP',
      status: 'Error',
      statusType: 'error',
      state: false,
    },
    {
      creditAccount: '1019833913',
      suppliers: 'Cody Fisher',
      beneficiaryType: 'Otro banco',
      bankId: '10153234',
      amount: 999999999.99,
      coin: 'USD',
      status: 'Error',
      statusType: 'error',
      state: false,
    },
    {
      creditAccount: '1019832343',
      suppliers: 'Bessie Cooper',
      beneficiaryType: 'APAP',
      bankId: '10153123',
      amount: 999999999.99,
      coin: 'USD',
      status: 'Correcto',
      statusType: 'info',
      state: false,
    },
    {
      creditAccount: '1012343265',
      suppliers: 'Robert Fox',
      beneficiaryType: 'Otro banco',
      bankId: '10112353',
      amount: 999999999.99,
      coin: 'USD',
      status: 'Correcto',
      statusType: 'info',
      state: false,
    },
    {
      creditAccount: '1019402748',
      suppliers: 'Cameron Williamson',
      beneficiaryType: 'Otro banco',
      bankId: '10112367',
      amount: 999999999.99,
      coin: 'USD',
      status: 'Correcto',
      statusType: 'info',
      state: false,
    },
    {
      creditAccount: '99999999999',
      suppliers: 'Jane Cooper',
      beneficiaryType: 'APAP',
      bankId: '10101010',
      amount: 999999999.99,
      coin: 'DOP',
      status: 'Correcto',
      statusType: 'info',
      state: false,
    },
    {
      creditAccount: '99999999999',
      suppliers: 'Jane Cooper',
      beneficiaryType: 'APAP',
      bankId: '10101010',
      amount: 999999999.99,
      coin: 'DOP',
      status: 'Correcto',
      statusType: 'info',
      state: false,
    },
    {
      creditAccount: '99999999999',
      suppliers: 'Jane Cooper',
      beneficiaryType: 'APAP',
      bankId: '10101010',
      amount: 999999999.99,
      coin: 'DOP',
      status: 'Correcto',
      statusType: 'info',
      state: false,
    },
    {
      creditAccount: '99999999999',
      suppliers: 'Jane Cooper',
      beneficiaryType: 'APAP',
      bankId: '10101010',
      amount: 999999999.99,
      coin: 'USD',
      status: 'Correcto',
      statusType: 'info',
      state: false,
    },
    {
      creditAccount: '99999999999',
      suppliers: 'Jane Cooper',
      beneficiaryType: 'APAP',
      bankId: '10101010',
      amount: 999999999.99,
      coin: 'DOP',
      status: 'Correcto',
      statusType: 'info',
      state: false,
    },
    {
      creditAccount: '99999999999',
      suppliers: 'Jane Cooper',
      beneficiaryType: 'APAP',
      bankId: '10101010',
      amount: 999999999.99,
      coin: 'DOP',
      status: 'Correcto',
      statusType: 'info',
      state: false,
    },
    {
      creditAccount: '99999999999',
      suppliers: 'Jane Cooper',
      beneficiaryType: 'APAP',
      bankId: '10101010',
      amount: 999999999.99,
      coin: 'DOP',
      status: 'Correcto',
      statusType: 'info',
      state: false,
    },
    {
      creditAccount: '99999999999',
      suppliers: 'Jane Cooper',
      beneficiaryType: 'APAP',
      bankId: '10101010',
      amount: 999999999.99,
      coin: 'DOP',
      status: 'Error',
      statusType: 'error',
      state: false,
    },
    {
      creditAccount: '99999999999',
      suppliers: 'Jane Cooper',
      beneficiaryType: 'APAP',
      bankId: '10101010',
      amount: 999999999.99,
      coin: 'DOP',
      status: 'Error',
      statusType: 'error',
      state: false,
    },
    {
      creditAccount: '99999999999',
      suppliers: 'Jane Cooper',
      beneficiaryType: 'APAP',
      bankId: '10101010',
      amount: 999999999.99,
      coin: 'DOP',
      status: 'Error',
      statusType: 'error',
      state: false,
    },
    {
      creditAccount: '99999999999',
      suppliers: 'Jane Cooper',
      beneficiaryType: 'APAP',
      bankId: '10101010',
      amount: 999999999.99,
      coin: 'DOP',
      status: 'Error',
      statusType: 'error',
      state: false,
    },
    {
      creditAccount: '99999999999',
      suppliers: 'Jane Cooper',
      beneficiaryType: 'APAP',
      bankId: '10101010',
      amount: 999999999.99,
      coin: 'DOP',
      status: 'Error',
      statusType: 'error',
      state: false,
    },
  ];

  public testArrayDataPersonalCreditCards: any[] = [
    {
      name: 'Amanda León Mont...',
      cardNumber: '•••• 1234',
      limit: '$1,000,000.00',
      balanceDue: '$100,000.00',
      available: '$100,000.00',
    },
    {
      name: 'Amanda León Mont...',
      cardNumber: '•••• 1234',
      limit: '$1,000,000.00',
      balanceDue: '$284,299.99',
      available: '$284,299.99',
    },
  ];

  public testArrayDataLoans: any[] = [
    {
      noLoan: '100029384984',
      type: 'Vivienda',
      actualBalance: '$1,000,000.00 DOP ',
      unpaidBalance: '$100,000.00',
      share: '$100,000.00',
      limitPayment: '12/12/21',
    },
    {
      noLoan: '100029384984',
      type: 'Vivienda',
      actualBalance: '$1,000,000.00 DOP ',
      unpaidBalance: '$100,000.00',
      share: '$100,000.00',
      limitPayment: '12/12/21',
    },
  ];

  public testArrayDataCertificatesHome: any[] = [
    {
      noCf: '100378340',
      rate: '7%',
      originalMount: '$100,000.00',
      availableBalance: '$100,000.00',
      limitPayment: '12/12/21',
      alertState: 'nonAlert',
    },
    {
      noCf: '100378340',
      rate: '10%',
      originalMount: '$284,299.99',
      availableBalance: '$284,299.99',
      limitPayment: '12/12/21',
      alertState: 'alert',
    },
  ];

  public testArrayDataBankingInsuranceHome: any[] = [
    {
      noPolicy: '100029384984',
      policyName: 'Vivienda',
      mount: '$1,000,000.00 DOP ',
      limitPayment: '12/12/21',
      status: 'Cancelada',
      statusType: 'error',
    },
    {
      noPolicy: '100029384984',
      policyName: 'Vivienda',
      mount: '$1,000,000.00 DOP ',
      limitPayment: '12/12/21',
      status: 'Suspendida',
      statusType: 'warning',
    },
    {
      noPolicy: '100029384984',
      policyName: 'Vivienda',
      mount: '$1,000,000.00 DOP ',
      limitPayment: '12/12/21',
      status: 'Pendiente',
      statusType: 'pending',
    },
    {
      noPolicy: '100029384984',
      policyName: 'Vivienda',
      mount: '$1,000,000.00 DOP ',
      limitPayment: '12/12/21',
      status: 'Activa',
      statusType: 'active',
    },
  ];

  public testArrayDataTransactionHistory: any[] = [
    {
      transactionDate: '7 Dic. 2019',
      paymentDate: '7 Ene. 2020',
      cardNumber: '1234 •••• 1234',
      user: 'Jane Cooper',
      commerce: 'Dr impuesto DGII 0.0015',
      amount: -23999.99,
      currency: 'DOP',
      status: 'Rechazado',
      statusType: 'error',
      state: false,
    },
    {
      transactionDate: '7 Dic. 2019',
      paymentDate: '7 Ene. 2020',
      cardNumber: '1234 •••• 1234',
      user: 'Robert Fox',
      commerce: 'Transf. Interbancaria Cta.',
      amount: 999999999.99,
      currency: 'DOP',
      status: 'En tránsito',
      statusType: 'warning',
      state: false,
    },
    {
      transactionDate: '7 Dic. 2019',
      paymentDate: '7 Ene. 2020',
      cardNumber: '1234 •••• 1234',
      user: 'Cody Fisher',
      commerce: 'Crédito nómina',
      amount: 999999999.99,
      currency: 'USD',
      status: 'En tránsito',
      statusType: 'warning',
      state: false,
    },
    {
      transactionDate: '7 Dic. 2019',
      paymentDate: '7 Ene. 2020',
      cardNumber: '1234 •••• 1234',
      user: 'Bessie Cooper',
      commerce: 'Retiro en Atm no propio',
      amount: 999999999.99,
      currency: 'USD',
      status: 'Autorizado',
      statusType: 'info',
      state: false,
    },
    {
      transactionDate: '7 Dic. 2019',
      paymentDate: '7 Ene. 2020',
      cardNumber: '1234 •••• 1234',
      user: 'Robert Fox',
      commerce: 'Com. Retiro Atm Otro Banco',
      amount: 999999999.99,
      currency: 'USD',
      status: 'Autorizado',
      statusType: 'info',
      state: false,
    },
    {
      transactionDate: '7 Dic. 2019',
      paymentDate: '7 Ene. 2020',
      cardNumber: '1234 •••• 1234',
      user: 'Cameron Williamson',
      commerce: 'Dr impuesto DGII 0.0015',
      amount: 999999999.99,
      currency: 'USD',
      status: 'Autorizado',
      statusType: 'info',
      state: false,
    },
  ];

  public testArrayDataPayments: any[] = [
    {
      transactionDate: '7 Dic. 2019',
      amount: -23999.99,
      currency: 'USD',
      paymentChanel: 'Canal de pago',
      paymentApplication: 'dd/mm/aa',
    },
    {
      transactionDate: '7 Dic. 2019',
      amount: -23999.99,
      currency: 'USD',
      paymentChanel: 'Canal de pago',
      paymentApplication: '5/27/15',
    },
    {
      transactionDate: '7 Dic. 2019',
      amount: -23999.99,
      currency: 'USD',
      paymentChanel: 'Canal de pago',
      paymentApplication: '12/10/13',
    },
    {
      transactionDate: '7 Dic. 2019',
      amount: 999999999.99,
      currency: 'USD',
      paymentChanel: 'Canal de pago',
      paymentApplication: '10/6/13',
    },
    {
      transactionDate: '7 Dic. 2019',
      amount: 999999999.99,
      currency: 'USD',
      paymentChanel: 'Canal de pago',
      paymentApplication: '8/30/14',
    },
    {
      transactionDate: '7 Dic. 2019',
      amount: 999999999.99,
      currency: 'USD',
      paymentChanel: 'Canal de pago',
      paymentApplication: '1/15/12',
    },
  ];

  public testArrayDataAmountConsumed: any[] = [
    {
      transactionDate: 'dd/mm/aa',
      commerce: 'Dr impuesto DGII 0.0015',
      dueDate: 'dd/mm/aa',
      amount: 999999999.99,
      currency: 'DOP',
    },
    {
      transactionDate: '7 Dic. 2019',
      commerce: 'Transf. Interbancaria Cta.',
      dueDate: '7/Ene/2020',
      amount: 999999999.99,
      currency: 'DOP',
    },
    {
      transactionDate: '7 Dic. 2019',
      commerce: 'Crédito nómina',
      dueDate: '7/Ene/2020',
      amount: 999999999.99,
      currency: 'USD',
    },
    {
      transactionDate: '7 Dic. 2019',
      commerce: 'Retiro en Atm no propio',
      dueDate: '7/Ene/2020',
      amount: 999999999.99,
      currency: 'USD',
    },
    {
      transactionDate: '7 Dic. 2019',
      commerce: 'Com. Retiro Atm Otro Banco',
      dueDate: '7/Ene/2020',
      amount: 999999999.99,
      currency: 'USD',
    },
    {
      transactionDate: '7 Dic. 2019',
      commerce: 'Dr impuesto DGII 0.0015',
      dueDate: '7/Ene/2020',
      amount: 999999999.99,
      currency: 'USD',
    },
  ];

  public testArrayDataCardPayments: any[] = [
    {
      transactionDate: '7/Dic/2019',
      paymentDate: '7/Ene/2020',
      commerce: 'Dr impuesto DGII 0.0015',
      dueDate: '7/Ene/2020',
      balance: -999999999.99,
      currency: 'DOP',
    },
    {
      transactionDate: '7/Dic/2019',
      paymentDate: '7/Ene/2020',
      commerce: 'Transf. Interbancaria Cta.',
      dueDate: '7/Ene/2020',
      balance: -999999999.99,
      currency: 'DOP',
    },
    {
      transactionDate: '7/Dic/2019',
      paymentDate: '7/Ene/2020',
      commerce: 'Crédito nómina',
      dueDate: '7/Ene/2020',
      balance: -999999999.99,
      currency: 'USD',
    },
    {
      transactionDate: '7/Dic/2019',
      paymentDate: '7/Ene/2020',
      commerce: 'Retiro en Atm no propio',
      dueDate: '7/Ene/2020',
      balance: 999999999.99,
      currency: 'USD',
    },
    {
      transactionDate: '7/Dic/2019',
      paymentDate: '7/Ene/2020',
      commerce: 'Com. Retiro Atm Otro Banco',
      dueDate: '7/Ene/2020',
      balance: 999999999.99,
      currency: 'USD',
    },
    {
      transactionDate: '7/Dic/2019',
      paymentDate: '7/Ene/2020',
      commerce: 'Dr impuesto DGII 0.0015',
      dueDate: '7/Ene/2020',
      balance: 999999999.99,
      currency: 'USD',
    },
  ];

  public testArrayDataNfcConsultation: any[] = [
    {
      date: 'dd/mm/aa',
      type: 'Nota drédito Electróniica',
      ncfNumber: 'E34000000001',
      dni: '001-0000000-1',
      description: 'Pago comercio',
      expiration: '05/08/21',
      amount: 25500,
      itbis: 4590,
    },
    {
      date: '09 Dic.2021',
      type: 'Nota drédito Electróniica',
      ncfNumber: 'E34000000001',
      dni: '001-1242345-1',
      description: 'Pago comercio',
      expiration: '05/08/21',
      amount: 25500,
      itbis: 4590,
    },
    {
      date: '09 Dic.2021',
      type: 'Nota drédito Electróniica',
      ncfNumber: 'E34000000001',
      dni: '001-1242345-1',
      description: 'Pago comercio',
      expiration: '05/08/21',
      amount: 25500,
      itbis: 4590,
    },
    {
      date: '09 Dic.2021',
      type: 'Nota drédito Electróniica',
      ncfNumber: 'E34000000001',
      dni: '001-1242345-1',
      description: 'Pago comercio',
      expiration: '05/08/21',
      amount: 25500,
      itbis: 4590,
    },
    {
      date: '09 Dic.2021',
      type: 'Nota drédito Electróniica',
      ncfNumber: 'E34000000001',
      dni: '001-1242345-1',
      description: 'Pago comercio',
      expiration: '05/08/21',
      amount: 25500,
      itbis: 4590,
    },
    {
      date: '09 Dic.2021',
      type: 'Nota drédito Electróniica',
      ncfNumber: 'E34000000001',
      dni: '001-1242345-1',
      description: 'Pago comercio',
      expiration: '05/08/21',
      amount: 25500,
      itbis: 4590,
    },
    {
      date: '09 Dic.2021',
      type: 'Nota drédito Electróniica',
      ncfNumber: 'E34000000001',
      dni: '001-1242345-1',
      description: 'Pago comercio',
      expiration: '05/08/21',
      amount: 25500,
      itbis: 4590,
    },
    {
      date: '09 Dic.2021',
      type: 'Nota drédito Electróniica',
      ncfNumber: 'E34000000001',
      dni: '001-1242345-1',
      description: 'Pago comercio',
      expiration: '05/08/21',
      amount: 25500,
      itbis: 4590,
    },
    {
      date: '09 Dic.2021',
      type: 'Nota drédito Electróniica',
      ncfNumber: 'E34000000001',
      dni: '001-1242345-1',
      description: 'Pago comercio',
      expiration: '05/08/21',
      amount: 25500,
      itbis: 4590,
    },
  ];

  public testArrayDataSubordinateCards: any[] = [
    {
      cardNumber: '1234 •••• 1234',
      user: 'Jane Cooper',
      creditLimit: 999999999.99,
      availableCredit: 999999999.99,
      balance: 999999999.99,
      minimumPayment: 999999999.99,
      status: 'Bloqueada',
      statusType: 'blocked',
      state: false,
    },
    {
      cardNumber: '1234 •••• 1234',
      user: 'Robert Fox',
      creditLimit: 999999999.99,
      availableCredit: 999999999.99,
      balance: 999999999.99,
      minimumPayment: 999999999.99,
      status: 'Sobregirada',
      statusType: 'warning',
      state: false,
    },
    {
      cardNumber: '1234 •••• 1234',
      user: 'Cody Fisher',
      creditLimit: 999999999.99,
      availableCredit: 999999999.99,
      balance: 999999999.99,
      minimumPayment: 999999999.99,
      status: 'Inactiva',
      statusType: 'error',
      state: false,
    },
    {
      cardNumber: '1234 •••• 1234',
      user: 'Bessie Cooper',
      creditLimit: 999999999.99,
      availableCredit: 999999999.99,
      balance: 999999999.99,
      minimumPayment: 999999999.99,
      status: 'Activa',
      statusType: 'info',
      state: false,
    },
    {
      cardNumber: '1234 •••• 1234',
      user: 'Robert Fox',
      creditLimit: 999999999.99,
      availableCredit: 999999999.99,
      balance: 999999999.99,
      minimumPayment: 999999999.99,
      status: 'Activa',
      statusType: 'info',
      state: false,
    },
    {
      cardNumber: '1234 •••• 1234',
      user: 'Cameron Williamson',
      creditLimit: 999999999.99,
      availableCredit: 999999999.99,
      balance: 999999999.99,
      minimumPayment: 999999999.99,
      status: 'Activa',
      statusType: 'info',
      state: false,
    },
  ];

  public testArrayDataTransactionHistoryStatus: any[] = [
    {
      transactionDate: '7 Dic. 2019',
      paymentDate: '7 Ene. 2020',
      cardNumber: '1234 •••• 1234',
      user: 'Jane Cooper',
      commerce: 'Dr impuesto DGII 0.0015',
      amount: -23999.99,
      currency: 'DOP',
      status: 'Rechazado',
      statusType: 'error',
      state: false,
    },
    {
      transactionDate: '7 Dic. 2019',
      paymentDate: '7 Ene. 2020',
      cardNumber: '1234 •••• 1234',
      user: 'Robert Fox',
      commerce: 'Transf. Interbancaria Cta.',
      amount: 999999999.99,
      currency: 'DOP',
      status: 'Proceso',
      statusType: 'warning',
      state: false,
    },
    {
      transactionDate: '7 Dic. 2019',
      paymentDate: '7 Ene. 2020',
      cardNumber: '1234 •••• 1234',
      user: 'Cody Fisher',
      commerce: 'Crédito nómina',
      amount: 999999999.99,
      currency: 'USD',
      status: 'Aplicado',
      statusType: 'success',
      state: false,
    },
    {
      transactionDate: '7 Dic. 2019',
      paymentDate: '7 Ene. 2020',
      cardNumber: '1234 •••• 1234',
      user: 'Bessie Cooper',
      commerce: 'Retiro en Atm no propio',
      amount: 999999999.99,
      currency: 'USD',
      status: 'Enviado',
      statusType: 'info',
      state: false,
    },
    {
      transactionDate: '7 Dic. 2019',
      paymentDate: '7 Ene. 2020',
      cardNumber: '1234 •••• 1234',
      user: 'Robert Fox',
      commerce: 'Com. Retiro Atm Otro Banco',
      amount: 999999999.99,
      currency: 'USD',
      status: 'Enviado',
      statusType: 'info',
      state: false,
    },
    {
      transactionDate: '7 Dic. 2019',
      paymentDate: '7 Ene. 2020',
      cardNumber: '1234 •••• 1234',
      user: 'Cameron Williamson',
      commerce: 'Dr impuesto DGII 0.0015',
      amount: 999999999.99,
      currency: 'USD',
      status: 'Enviado',
      statusType: 'info',
      state: false,
    },
  ];

  public testArrayDataAditionalSubordinateCards: any[] = [
    {
      transactionDate: 'dd/mm/aa',
      commerce: 'Dr impuesto DGII 0.0015',
      amount: -23999.99,
      currency: 'DOP',
      statusRigth: 'Rechazado',
      statusType: 'error',
      state: false,
    },
    {
      transactionDate: '7/11/19',
      commerce: 'Transf. Interbancaria Cta.',
      amount: 999999999.99,
      currency: 'DOP',
      statusRigth: 'Proceso',
      statusType: 'warning',
      state: false,
    },
    {
      transactionDate: '6/21/19',
      commerce: 'Crédito nómina',
      amount: 999999999.99,
      currency: 'USD',
      statusRigth: 'Aplicado',
      statusType: 'success',
      state: false,
    },
    {
      transactionDate: '4/4/18',
      commerce: 'Retiro en Atm no propio',
      amount: 999999999.99,
      currency: 'USD',
      statusRigth: 'Enviado',
      statusType: 'info',
      state: false,
    },
    {
      transactionDate: '12/4/17',
      commerce: 'Com. Retiro Atm Otro Banco',
      amount: 999999999.99,
      currency: 'USD',
      statusRigth: 'Enviado',
      statusType: 'info',
      state: false,
    },
    {
      transactionDate: '8/15/17',
      commerce: 'Dr impuesto DGII 0.0015',
      amount: 999999999.99,
      currency: 'USD',
      statusRigth: 'Enviado',
      statusType: 'info',
      state: false,
    },
  ];

  public testArrayDataAccountStatus: any[] = [
    {
      transactionDate: '7 Dic. 2019',
      paymentDate: '7 Ene. 2020',
      cardNumber: '1234 •••• 1234',
      user: 'Jane Cooper',
      commerce: 'Dr impuesto DGII 0.0015',
      amount: -23999.99,
      currency: 'DOP',
      status: 'Rechazado',
      statusType: 'error',
      state: false,
    },
    {
      transactionDate: '7 Dic. 2019',
      paymentDate: '7 Ene. 2020',
      cardNumber: '1234 •••• 1234',
      user: 'Robert Fox',
      commerce: 'Transf. Interbancaria Cta.',
      amount: 999999999.99,
      currency: 'DOP',
      status: 'Proceso',
      statusType: 'warning',
      state: false,
    },
    {
      transactionDate: '7 Dic. 2019',
      paymentDate: '7 Ene. 2020',
      cardNumber: '1234 •••• 1234',
      user: 'Cody Fisher',
      commerce: 'Crédito nómina',
      amount: 999999999.99,
      currency: 'USD',
      status: 'Aplicado',
      statusType: 'success',
      state: false,
    },
    {
      transactionDate: '7 Dic. 2019',
      paymentDate: '7 Ene. 2020',
      cardNumber: '1234 •••• 1234',
      user: 'Bessie Cooper',
      commerce: 'Retiro en Atm no propio',
      amount: 999999999.99,
      currency: 'USD',
      status: 'Enviado',
      statusType: 'info',
      state: false,
    },
    {
      transactionDate: '7 Dic. 2019',
      paymentDate: '7 Ene. 2020',
      cardNumber: '1234 •••• 1234',
      user: 'Robert Fox',
      commerce: 'Com. Retiro Atm Otro Banco',
      amount: 999999999.99,
      currency: 'USD',
      status: 'Enviado',
      statusType: 'info',
      state: false,
    },
    {
      transactionDate: '7 Dic. 2019',
      paymentDate: '7 Ene. 2020',
      cardNumber: '1234 •••• 1234',
      user: 'Cameron Williamson',
      commerce: 'Dr impuesto DGII 0.0015',
      amount: 999999999.99,
      currency: 'USD',
      status: 'Enviado',
      statusType: 'info',
      state: false,
    },
    {
      transactionDate: '7 Dic. 2019',
      paymentDate: '7 Ene. 2020',
      cardNumber: '1234 •••• 1234',
      user: 'Ralph Edwards',
      commerce: 'Dr impuesto DGII 0.0015',
      amount: 999999999.99,
      currency: 'DOP',
      status: 'Enviado',
      statusType: 'info',
      state: false,
    },
  ];

  public testArrayDataCashback: any[] = [
    {
      receiveCashbackDate: 'dd/mm/aa',
      receiveCashbackAmmount: 999999999.99,
      description: 'Dr impuesto DGII 0.0015',
      cardNumber: '1234 •••• 1234',
      user: 'Jane Cooper',
      cardType: 'Tarjeta principal',
      state: false,
    },
    {
      receiveCashbackDate: '7 Nov. 2021',
      receiveCashbackAmmount: 999999999.99,
      description: 'Transf. Interbancaria Cta.',
      cardNumber: '1234 •••• 1234',
      user: 'Robert Fox',
      cardType: 'Tarjeta adicional',
      state: false,
    },
    {
      receiveCashbackDate: '7 Nov. 2021',
      receiveCashbackAmmount: 999999999.99,
      description: 'Crédito nómina',
      cardNumber: '1234 •••• 1234',
      user: 'Cody Fisher',
      cardType: 'Tarjeta principal',
      state: false,
    },
    {
      receiveCashbackDate: '7 Nov. 2021',
      receiveCashbackAmmount: 999999999.99,
      description: 'Retiro en Atm no propio',
      cardNumber: '1234 •••• 1234',
      user: 'Bessie Cooper',
      cardType: 'Tarjeta principal',
      state: false,
    },
    {
      receiveCashbackDate: '7 Nov. 2021',
      receiveCashbackAmmount: 999999999.99,
      description: 'Com. Retiro Atm Otro Banco',
      cardNumber: '1234 •••• 1234',
      user: 'Robert Fox',
      cardType: 'Tarjeta adicional',
      state: false,
    },
    {
      receiveCashbackDate: '7 Nov. 2021',
      receiveCashbackAmmount: 999999999.99,
      description: 'Dr impuesto DGII 0.0015',
      cardNumber: '1234 •••• 1234',
      user: 'Cameron Williamson',
      cardType: 'Tarjeta adicional',
      state: false,
    },
    {
      receiveCashbackDate: '7 Nov. 2021',
      receiveCashbackAmmount: 999999999.99,
      description: 'Dr impuesto DGII 0.0015',
      cardNumber: '1234 •••• 1234',
      user: 'Ralph Edwards',
      cardType: 'Tarjeta adicional',
      state: false,
    },
    {
      receiveCashbackDate: '7 Nov. 2021',
      receiveCashbackAmmount: 999999999.99,
      description: 'Dr impuesto DGII 0.0015',
      cardNumber: '1234 •••• 1234',
      user: 'Esther Howard',
      cardType: 'Tarjeta adicional',
      state: false,
    },
  ];

  public testArrayDataCreditCards: any[] = [
    {
      cardName: 'Visa infinite',
      cardNumber: '1234 •••• 1234',
      cards: [
        {
          cardNumber: '1234 •••• 1234',
          user: 'Alicia Diaz Contreras',
          isMainCard: true,
          buyingLimit: 9999999.99,
          advanceLimit: 9999999.99,
          status: 'Pendiente',
          statusType: 'pending',
          cardOptions: {
            usageParams: {
              local: false,
              international: false,
              onlinePayment: false,
              onlineInternationalPayment: false,
            },
            cardParams: {
              blocked: false,
              active: true,
              reportTrip: true,
            },
          },
        },
        {
          cardNumber: '1234 •••• 1233',
          user: 'Alicia Diaz Contreras',
          isMainCard: false,
          buyingLimit: 9999999.99,
          advanceLimit: 9999999.99,
          status: 'Bloqueada',
          statusType: 'blocked',
          cardOptions: {
            usageParams: {
              local: true,
              international: false,
              onlinePayment: false,
              onlineInternationalPayment: false,
            },
            cardParams: {
              blocked: true,
              active: false,
              reportTrip: false,
            },
          },
        },
        {
          cardNumber: '1234 •••• 1232',
          user: 'Alicia Diaz Contreras',
          isMainCard: false,
          buyingLimit: 9999999.99,
          advanceLimit: 9999999.99,
          status: 'Activa',
          statusType: 'active',
          cardOptions: {
            usageParams: {
              local: false,
              international: false,
              onlinePayment: true,
              onlineInternationalPayment: false,
            },
            cardParams: {
              blocked: true,
              active: false,
              reportTrip: false,
            },
          },
        },
      ],
    },
    {
      cardName: 'Nombre del producto',
      cardNumber: 'No. de tarjeta',
      cards: [
        {
          cardNumber: '1234 •••• 1234',
          user: 'Alicia Diaz Contreras',
          isMainCard: true,
          buyingLimit: 9999999.99,
          advanceLimit: 9999999.99,
          status: 'Pendiente',
          statusType: 'pending',
          cardOptions: {
            usageParams: {
              local: false,
              international: false,
              onlinePayment: false,
              onlineInternationalPayment: false,
            },
            cardParams: {
              blocked: true,
              active: false,
              reportTrip: false,
            },
          },
        },
        {
          cardNumber: '1234 •••• 1233',
          user: 'Alicia Diaz Contreras',
          isMainCard: false,
          buyingLimit: 9999999.99,
          advanceLimit: 9999999.99,
          status: 'Bloqueada',
          statusType: 'blocked',
          cardOptions: {
            usageParams: {
              local: false,
              international: false,
              onlinePayment: false,
              onlineInternationalPayment: false,
            },
            cardParams: {
              blocked: true,
              active: false,
              reportTrip: false,
            },
          },
        },
        {
          cardNumber: '1234 •••• 1232',
          user: 'Alicia Diaz Contreras',
          isMainCard: false,
          buyingLimit: 9999999.99,
          advanceLimit: 9999999.99,
          status: 'Activa',
          statusType: 'active',
          cardOptions: {
            usageParams: {
              local: false,
              international: false,
              onlinePayment: false,
              onlineInternationalPayment: false,
            },
            cardParams: {
              blocked: true,
              active: false,
              reportTrip: false,
            },
          },
        },
      ],
    },
    {
      cardName: 'Alicia Diaz Contreras',
      cardNumber: '1234 •••• 1234',
      cards: [
        {
          cardNumber: '1234 •••• 1234',
          user: 'Alicia Diaz Contreras',
          isMainCard: true,
          buyingLimit: 9999999.99,
          advanceLimit: 9999999.99,
          status: 'Pendiente',
          statusType: 'pending',
          cardOptions: {
            usageParams: {
              local: false,
              international: false,
              onlinePayment: false,
              onlineInternationalPayment: false,
            },
            cardParams: {
              blocked: true,
              active: false,
              reportTrip: false,
            },
          },
        },
        {
          cardNumber: '1234 •••• 1233',
          user: 'Alicia Diaz Contreras',
          isMainCard: false,
          buyingLimit: 9999999.99,
          advanceLimit: 9999999.99,
          status: 'Bloqueada',
          statusType: 'blocked',
          cardOptions: {
            usageParams: {
              local: false,
              international: false,
              onlinePayment: false,
              onlineInternationalPayment: false,
            },
            cardParams: {
              blocked: true,
              active: false,
              reportTrip: false,
            },
          },
        },
        {
          cardNumber: '1234 •••• 1232',
          user: 'Alicia Diaz Contreras',
          isMainCard: false,
          buyingLimit: 9999999.99,
          advanceLimit: 9999999.99,
          status: 'Activa',
          statusType: 'active',
          cardOptions: {
            usageParams: {
              local: false,
              international: false,
              onlinePayment: false,
              onlineInternationalPayment: false,
            },
            cardParams: {
              blocked: true,
              active: false,
              reportTrip: false,
            },
          },
        },
      ],
    },
  ];

  public testArrayDataCeritosReceived: any[] = [
    {
      product: 'Visa Infinite',
      productType: 'Tarjeta de crédito',
      totalCeritos: 999999.99,
      dopEquivalent: 999999.99,
      dueDate: 'dd/mm/aa',
    },
    {
      product: 'Mastercard Clásica Internacional',
      productType: 'Tarjeta de débito',
      totalCeritos: 999999.99,
      dopEquivalent: 999999.99,
      dueDate: '7 Nov. 2021',
    },
    {
      product: 'Débito gold',
      productType: 'Tarjeta de débito',
      totalCeritos: 999999.99,
      dopEquivalent: 999999.99,
      dueDate: '7 Nov. 2021',
    },
    {
      product: 'Visa Infinite',
      productType: 'Tarjeta de crédito',
      totalCeritos: 999999.99,
      dopEquivalent: 999999.99,
      dueDate: '7 Nov. 2021',
    },
    {
      product: 'Mastercard Clásica Internacional',
      productType: 'Tarjeta de crédito',
      totalCeritos: 999999.99,
      dopEquivalent: 999999.99,
      dueDate: '7 Nov. 2021',
    },
    {
      product: 'Mastercard Clásica Internacional',
      productType: 'Tarjeta de débito',
      totalCeritos: 999999.99,
      dopEquivalent: 999999.99,
      dueDate: '7 Nov. 2021',
    },
  ];

  public testArrayDataDetailCeritos: any[] = [
    {
      receiveCeritosDate: 'Ago 2020',
      generatedCeritos: 999999999.99,
      expiredCeritos: '999999.99',
      redeemedCeritos: 999.99,
      surrenderDate: 'dd/mm/aa',
    },
    {
      receiveCeritosDate: 'Jul 2020',
      generatedCeritos: 999999999.99,
      expiredCeritos: '-',
      redeemedCeritos: 234,
      surrenderDate: '5/27/15',
    },
    {
      receiveCeritosDate: 'Jun 2020',
      generatedCeritos: 999999999.99,
      expiredCeritos: '-',
      redeemedCeritos: 321,
      surrenderDate: '12/10/13',
    },
    {
      receiveCeritosDate: 'May 2020',
      generatedCeritos: 999999999.99,
      expiredCeritos: '-',
      redeemedCeritos: 923,
      surrenderDate: '10/6/13',
    },
    {
      receiveCeritosDate: 'Abr 2020',
      generatedCeritos: 999999999.99,
      expiredCeritos: '999999.99',
      redeemedCeritos: 999.99,
      surrenderDate: '8/30/14',
    },
    {
      receiveCeritosDate: 'Mar 2020',
      generatedCeritos: 999999999.99,
      expiredCeritos: '-',
      redeemedCeritos: '-',
      surrenderDate: '1/15/12',
    },
  ];

  public testArrayDataRegisteredDevices: any[] = [
    {
      icon: 'phone_iphone_black_2',
      device: 'Iphone X',
      name: 'Iphone de Amanda',
      ipAddress: '192.168.28.136',
      lastAccess: 'Activo ahora',
      status: 'Nuevo',
      statusType: 'info',
    },
    {
      icon: 'tablet_mac_black_24dp',
      device: 'Tablet Ipad',
      name: 'Tablet de Amanda',
      ipAddress: '192.168.28.136',
      lastAccess: '18/08/21',
      status: '',
      statusType: '',
    },
    {
      icon: 'phone_iphone_black_2',
      device: 'Samsung Galaxy S9+',
      name: 'Samsung de Amanda',
      ipAddress: '192.168.28.136',
      lastAccess: '18/08/21',
      status: '',
      statusType: '',
    },
    {
      icon: 'computer_black_24dp',
      device: 'Laptop Dell',
      name: 'Laptop de Amanda',
      ipAddress: '192.168.28.136',
      lastAccess: '18/08/21',
      status: '',
      statusType: '',
    },
    {
      icon: 'phone_iphone_black_2',
      device: 'Samsung Galaxy S9+',
      name: 'Samsung de Amanda',
      ipAddress: '192.168.28.136',
      lastAccess: '18/08/21',
      status: '',
      statusType: '',
    },
    {
      icon: 'computer_black_24dp',
      device: 'iMac 2013',
      name: 'iMac de Amanda',
      ipAddress: '192.168.28.136',
      lastAccess: '18/08/21',
      status: '',
      statusType: '',
    },
  ];

  public testArrayDataDeviceHistory: any[] = [
    {
      device: 'Iphone X',
      ipAddress: '192.168.28.136',
      bindingDate: '18/08/21',
      terminationDate: '18/08/21',
    },
    {
      device: 'Samsung Galaxy S9+',
      ipAddress: '192.168.28.136',
      bindingDate: '18/08/21',
      terminationDate: '18/08/21',
    },
    {
      device: 'Samsung Galaxy S9+',
      ipAddress: '192.168.28.136',
      bindingDate: '18/08/21',
      terminationDate: '18/08/21',
    },
    {
      device: 'Samsung Galaxy S9+',
      ipAddress: '192.168.28.136',
      bindingDate: '18/08/21',
      terminationDate: '18/08/21',
    },
    {
      device: 'Samsung Galaxy S9+',
      ipAddress: '192.168.28.136',
      bindingDate: '18/08/21',
      terminationDate: '18/08/21',
    },
    {
      device: 'Samsung Galaxy S9+',
      ipAddress: '192.168.28.136',
      bindingDate: '18/08/21',
      terminationDate: '18/08/21',
    },
  ];

  public testArrayDataTPayment: any[] = [
    {
      telephoneCompany: 'Claro',
      number: '{Número de teléfono}',
      isActive: true,
      linkedProducts: [
        {
          productName: 'Nombre del producto',
          productType: 'Préstamo',
          balance: 999999.99,
          coin: 'DOP',
        },
        {
          productName: 'Nombre del producto',
          productType: 'Cuenta de ahorros',
          balance: 999999.99,
          coin: 'DOP',
        },
        {
          productName: 'Nombre del producto',
          productType: 'Tarjeta',
          balance: 999999.99,
          coin: 'DOP',
        },
      ],
    },
    {
      telephoneCompany: 'Altice',
      number: '{Número de teléfono}',
      isActive: false,
      linkedProducts: [
        {
          productName: 'Nombre del producto',
          productType: 'Préstamo',
          balance: 999999.99,
          coin: 'DOP',
        },
        {
          productName: 'Nombre del producto',
          productType: 'Cuenta de ahorros',
          balance: 999999.99,
          coin: 'DOP',
        },
        {
          productName: 'Nombre del producto',
          productType: 'Tarjeta',
          balance: 999999.99,
          coin: 'DOP',
        },
      ],
    },
  ];

  public textTransactionalArray: any[] = [
    {
      date: '02/02/2022',
      description: 'Dr impuesto DGII 0.0015',
      amount: -23999,
      balance: 999999999,
      fullName: 'Amanda León Montero',
      status: 'Rechazado',
      statusType: 'error',
      coin: 'DOP',
      channel: 'APP',
      state: false,
    },
    {
      date: '07/11/2019',
      description: 'Transf. Interbancaria Cta.',
      amount: 999999999,
      balance: 999999999,
      fullName: 'Amanda León Montero',
      status: 'Proceso',
      statusType: 'warning',
      coin: 'DOP',
      channel: 'IB',
      state: false,
    },
    {
      date: '06/21/2019',
      description: 'Transf. Interbancaria Cta.',
      amount: 999999999,
      balance: 999999999,
      fullName: 'Amanda León Montero',
      status: 'Aplicado',
      statusType: 'success',
      coin: 'USD',
      channel: 'APP',
      state: false,
    },
    {
      date: '04/04/2018',
      description: 'Retiro en Atm no propio',
      amount: 999999999,
      balance: 999999999,
      fullName: 'Amanda León Montero',
      status: 'Enviado',
      statusType: 'info',
      coin: 'USD',
      channel: 'Caja',
      state: false,
    },
    {
      date: '12/04/2017',
      description: 'Com. Retiro Atm Otro Banco',
      amount: 999999999,
      balance: 999999999,
      fullName: 'Amanda León Montero',
      status: 'Enviado',
      statusType: 'info',
      coin: 'USD',
      channel: 'Caja',
      state: false,
    },
    {
      date: '12/04/2017',
      description: 'Com. Retiro Atm Otro Banco',
      amount: 999999999,
      balance: 999999999,
      fullName: 'Amanda León Montero',
      status: 'Enviado',
      statusType: 'info',
      coin: 'USD',
      channel: 'Caja',
      state: false,
    },
    {
      date: '08/15/2017',
      description: 'Dr impuesto DGII 0.0015',
      amount: 999999999,
      balance: 999999999,
      fullName: 'Amanda León Montero',
      status: 'Enviado',
      statusType: 'info',
      coin: 'USD',
      channel: 'Caja',
      state: false,
    },
    {
      date: '08/15/2017',
      description: 'Dr impuesto DGII 0.0015',
      amount: 999999999,
      balance: 999999999,
      fullName: 'Amanda León Montero',
      status: 'Enviado',
      statusType: 'info',
      coin: 'USD',
      channel: 'Caja',
      state: false,
    },
    {
      date: '02/02/2022',
      description: 'Dr impuesto DGII 0.0015',
      amount: -23999,
      balance: 999999999,
      fullName: 'Amanda León Montero',
      status: 'Rechazado',
      statusType: 'error',
      coin: 'DOP',
      channel: 'APP',
      state: false,
    },
    {
      date: '07/11/2019',
      description: 'Transf. Interbancaria Cta.',
      amount: 999999999,
      balance: 999999999,
      fullName: 'Amanda León Montero',
      status: 'Proceso',
      statusType: 'warning',
      coin: 'DOP',
      channel: 'IB',
      state: false,
    },
    {
      date: '06/21/2019',
      description: 'Transf. Interbancaria Cta.',
      amount: 999999999,
      balance: 999999999,
      fullName: 'Amanda León Montero',
      status: 'Aplicado',
      statusType: 'success',
      coin: 'USD',
      channel: 'APP',
      state: false,
    },
    {
      date: '04/04/2018',
      description: 'Retiro en Atm no propio',
      amount: 999999999,
      balance: 999999999,
      fullName: 'Amanda León Montero',
      status: 'Enviado',
      statusType: 'info',
      coin: 'USD',
      channel: 'Caja',
      state: false,
    },
    {
      date: '06/21/2019',
      description: 'Transf. Interbancaria Cta.',
      amount: 999999999,
      balance: 999999999,
      fullName: 'Amanda León Montero',
      status: 'Aplicado',
      statusType: 'success',
      coin: 'USD',
      channel: 'APP',
      state: false,
    },
    {
      date: '04/04/2018',
      description: 'Retiro en Atm no propio',
      amount: 999999999,
      balance: 999999999,
      fullName: 'Amanda León Montero',
      status: 'Enviado',
      statusType: 'info',
      coin: 'USD',
      channel: 'Caja',
      state: false,
    },
    {
      date: '02/02/2020',
      description: 'Dr impuesto DGII 0.0015',
      amount: -23999,
      balance: 999999999,
      fullName: 'Amanda León Montero',
      status: 'Rechazado',
      statusType: 'error',
      coin: 'DOP',
      channel: 'APP',
      state: false,
    },
    {
      date: '05/05/2021',
      description: 'Dr impuesto DGII 0.0015',
      amount: -23999,
      balance: 999999999,
      fullName: 'Amanda León Montero',
      status: 'Rechazado',
      statusType: 'error',
      coin: 'DOP',
      channel: 'APP',
      state: false,
    },
    {
      date: '04/04/2019',
      description: 'Retiro en Atm no propio',
      amount: 999999999,
      balance: 999999999,
      fullName: 'Amanda León Montero',
      status: 'Enviado',
      statusType: 'info',
      coin: 'USD',
      channel: 'Caja',
      state: false,
    },
  ];

  public testSourceAccountArray: any[] = [
    {
      account: 1019315563,
      type: 'APAP',
    },
    {
      account: 41248548589,
      type: 'OTHER',
    },
  ];
}
